name: Android CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # Trigger the workflow only on tag pushes (e.g., v1.0.0)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Specify the version your project uses

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant gradlew permission
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33 # Target API level
          build-tools: '33.0.2'
          target: 'android-33'

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Debug properties
        run: echo "Store file ${{ secrets.ANDROID_KEYSTORE }}" && echo "Alias ${{ secrets.ANDROID_KEY_ALIAS }}"

      # Decode keystore
      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > keystore-project.jks

      - name: Debug Token Scope
        run: |
          curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases


      # Build signed Release APK
      - name: Build signed release APK
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=keystore-project.jks -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          ACTIONS_STEP_DEBUG: true


      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Use the pushed tag as the release tag
          release_name: "Release ${{ github.ref_name }}"
          body: |
            Release details for version ${{ github.ref_name }}.
            - Built on: ${{ github.event.head_commit.timestamp }}
            - Commit: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive

      # Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

